language: objective-c
notifications:
  email: false
install:
  - cd Examples
script:
  - xctool -project SlidingPanelController.xcodeproj -scheme 'SlidingPanelController' -configuration Release -sdk iphonesimulator -arch i386 build
  - xctool -project SlidingPanelControllerStoryboard.xcodeproj -scheme 'SlidingPanelControllerStoryboard' -configuration Release -sdk iphonesimulator -arch i386 build
